version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: shl-redis

  # backend:
  #   build: ./packages/backend
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./packages/backend:/home/backend
  #   container_name: SimpleCms-backend
  #
  # frontend:
  #   build: ./packages/frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./packages/frontend:/app
  #   container_name: SimpleCms-frontend
  #   stdin_open: true
